trtexec \
    --onnx=./onnx_zoo/SwinIR_LN_mask_Gelu.onnx \
    --minShapes=imgs:1x3x256x256 \
    --optShapes=imgs:4x3x256x256 \
    --maxShapes=imgs:8x3x256x256 \
    --workspace=20480 \
    --saveEngine=SwinIR_dynamic.plan \
    --shapes=imgs:4x3x256x256 \
    --plugins=./plugin/LayerNormPlugin-V2.2-CUB-TRT8/LayerNormPlugin.so \
    --plugins=./plugin/WindowsMaskPlugin-V2-HX/WindowsMaskPlugin.so \
    --plugins=./plugin/GeluPlugin-V1-HX/GeluPlugin.so\